# Generated by Django 4.2.3 on 2023-08-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todop1', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='Desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='status',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='target',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
